version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dragofire
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=docker
